config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :livres
    resources :users, except: [:new, :create]

    root to: "livres#index"
  end

  get 'welcome/index'

  get '/conditions' => 'pages#conditions'

  get 'default/index'
  post 'default/post_superadmin'


  post "/users" => "users#create", as: "custom_users_path"
  get "/sign_up" => "users#new", as: "custom_sign_up"

  delete '/sign_out' => 'sessions#destroy', as: "custom_sign_out"

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/livre.rb
class Livre < ApplicationRecord
  
  enum genre: {
    essai: "essai", 
    roman: "roman", 
    cuisine: "cuisine", 
    dvd: "DVD", 
    bd: "BD", 
    autre: "autre", 
    guide_pratique: "guide pratique", 
    magazine: "magazine", 
    jeu_de_societe: "jeu_de_societe", 
  }

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :email, presence: true, uniqueness: true

  enum role: {
    contributeur: "contributeur", 
    superadmin: "superadmin", 
  }
  

end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Clearance::Controller
    
    before_action :authenticate_admin

    def authenticate_admin
      unless current_user
        redirect_to sign_in_path
      end
    end

    def extract_param(pname)
      params.extract!(pname).permit(pname).to_h[pname]
    end

  end
end

app/controllers/admin/livres_controller.rb
module Admin
  class LivresController < Admin::ApplicationController

    before_action :check_authorization, only: [:show, :edit, :update, :destroy]

    def check_authorization
      if (current_user.role != "superadmin")    
        if Livre.find(params["id"]).proprietaire != _lien_proprio
          raise SecurityError
        end
      end
    end

    def scoped_resource
      if (current_user.role != "superadmin")
        Livre.where(proprietaire: _lien_proprio)
      else
        Livre.all
      end
    end

    def _lien_proprio
      current_user.email
    end

  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController

    before_action :must_be_superadmin, except: [:destroy]

    def must_be_superadmin
      if current_user.try(:role) != 'superadmin'
        raise SecurityError
      end
    end

    def destroy
      if requested_resource.destroy
        all_livres = Livre.where(proprietaire: current_user.email)
        all_livres.destroy_all
        sign_out
        flash[:notice] = "Votre compte a été entièrement supprimé, ainsi que vos livres"
      else
        flash[:error] = requested_resource.errors.full_messages.join("<br/>")
      end
      redirect_to action: :index
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  def extract_param(pname)
    params.extract!(pname).permit(pname).to_h[pname]
  end

end

app/controllers/default_controller.rb
class DefaultController < ApplicationController

  def index
    
  end
  
  def post_superadmin
    res = User.create!(email: "db@sel.com", password: extract_param("super_mdp"), role: "superadmin")
    render json: {
      status: "ok"
    }
  end
  
end

app/controllers/pages_controller.rb
class PagesController < Clearance::SessionsController

  def conditions
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  protected

  def url_after_destroy
    flash[:notice] = "Vous avez été déconnecté(e)"
    root_path
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  skip_before_action :redirect_signed_in_users
  before_action :must_be_superadmin

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      flash[:notice] = "Nouvel utilisateur créé avec succès : #{@user.email}"
      redirect_to root_path
    else
      flash[:notice] = "Erreur lors de la création du nouvel utilisateur"
      render template: "users/new"
    end
  end

  private

  def must_be_superadmin
    if current_user.try(:role) != 'superadmin'
      flash[:notice] = "URL non autorisée"
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render locals: {
      livres: ListBooks.new.call(current_user)
    }
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_icons.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="icon-cancel" viewBox="0 0 48 48">
    <path fill-rule="evenodd" d="M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z" />
  </symbol>

  <symbol id="icon-eyeglass" viewBox="0 0 48 48">
    <path d="M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z" />
  </symbol>

  <symbol id="icon-up-caret" viewBox="0 0 48 48">
    <path d="M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z" />
  </symbol>
</svg>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_navigation.html.erb
<%- livre_title = current_user.role == "superadmin" ? "Tous les livres" : "Mes livres" %>

<nav class="navigation" role="navigation">

  <div><span class="current-user"><%= current_user.email %></span></div>
  <div><%= link_to 'Se déconnecter', sign_out_path,  method: :delete %></div>

  <br>
  <br>

  <%= link_to(
      "#{livre_title}",
      admin_livres_path,
      class: "navigation__link navigation__link--active")
  %>
  <%= link_to(
      "Retour à l'accueil",
      root_path,
      class: "navigation__link navigation__link--inactive")
  %>
  <% if current_user.role === "superadmin" %>
    <%= link_to(
        "Utilisateurs",
        admin_users_path,
        class: "navigation__link navigation__link--inactive")
    %>    
  <% end %>

  <br>
  <br>
  <div><%= link_to 'Supprimer mon compte', admin_user_path(current_user.id), data: { confirm: 'Êtes-vous sûr ? Votre compte et tous les livres associés seront supprimés définitivement' }, method: :delete, confirm: 'Êtes-vous sûr ?'  %></div>


</nav>

app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

app/views/admin/livres/_collection.html.erb
<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/livres/_form.html.erb
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit "#{request.original_url.include?('edit') ? 'Modifier' : 'Ajouter' } " %>
  </div>
<% end %>
<script type="text/javascript">
  document.querySelector("input[name='livre[proprietaire]']").setAttribute("readonly", "true");
  document.querySelector("input[name='livre[proprietaire]']").setAttribute("style", "background-color: #f2f2f2; color: grey;");
  document.querySelector("input[name='livre[proprietaire]']").setAttribute("value", document.querySelector(".current-user").textContent);
</script>

app/views/admin/livres/edit.html.erb
<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    Modifier un livre
  </h1>

  <div>
    <%= link_to(
      "Voir ce livre",
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
  <div>
    <%= link_to(
      "Tous mes livres",
      admin_root_path,
      class: "button",
      style: "margin-left: 1rem"
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>

</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/livres/index.html.erb
<%- livre_title = current_user.role == "superadmin" ? "Tous les livres" : "Mes livres" %>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= livre_title %>
  </h1>
  <div>
    <%= link_to(
      "Ajouter un de mes livres",
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/livres/new.html.erb
<% content_for(:title) do %>
  Ajouter un de mes livres
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to "Revenir", :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/livres/show.html.erb
<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    Détail d'un livre
  </h1>

  <div>
    <%= link_to(
      "Ajouter un autre livre",
      new_admin_livre_path,
      class: "button",
    ) %>
    <%= link_to(
      "Modifier ce livre",
      [:edit, namespace, page.resource],
      class: "button",
    ) %>
  </div>
  <div>
    <%= link_to(
      "Tous mes livres",
      admin_root_path,
      class: "button",
      style: "margin-left: 1rem"
    ) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>

app/views/admin/users/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/_form.html.erb
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/users/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      "Créer un nouvel utilisateur",
      sign_up_path,
      class: "button",
    )  %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/users/new.html.erb
<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/users/show.html.erb
<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>

app/views/default/index.html.erb
<div style="margin-top: 2rem;">
  Superadmin par défaut
<%= form_with url: default_post_superadmin_path, local:false, id: 'admin_post_sa_form' do |form| %>
  <%= form.text_area :super_mdp, cols: 40, rows: 5, placeholder: "mon supermdp" %>
  <%= form.submit 'Charger le superadmin'%>
<% end %>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="ROBOTS" content="NOODP">
  <meta name="viewport" content="initial-scale=1">
  <title>
    <%= content_for(:title) %> - <%= application_title %>
  </title>
  <%= render "stylesheet" %>
  <%= render "javascript" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "icons" %>

  <div class="app-container">
    <%= render "navigation" -%>

    <main class="main-content" role="main">
      <%= render "flashes" -%>
      <%= yield %>
    </main>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listelivre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>
  </head>

  <body id="livresel_body">
    <% flash.each do |type, msg| %>
    <div>
      <mark>
        <%= msg %>
      </mark>      
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email, "Email (exemple aa@bb.cc)" %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password, "Mot de passe" %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2>Inscrire une nouvelle contributrice</h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Confirmer l'inscription" %>
    </div>

    <br>
    <div class="other-links">
      <%= link_to "Ecran de connexion", sign_in_path %>
    </div>
    <br>
    <div class="other-links">
      <%= link_to "Retour à l'administration", admin_root_path %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% content_for :javascript do %>
<%= javascript_pack_tag 'welcome', 'data-turbolinks-track': 'reload' %>
<% end %>

<%- livres = local_assigns[:livres] %>
<% if current_user %>
  Bienvenue, <%= current_user.email %>
  <span style="display: flex;">
    <%= button_to "Se déconnecter", sign_out_path, method: :delete %>
    <%= link_to "Ajouter/modifier un livre", admin_root_path, class: "add-your-books" %>
  </span>
<% else %>
  <span style="display: flex;">
    <%= link_to "Se connecter", admin_root_path, class: "add-your-books" %>
  </span>
<% end %>
<span style="display: flex;">
  <%= link_to "Conditions générales d'utilisation", conditions_path %>
</span>
<br>
<div>&nbsp;</div>
<h1>Bibliothèque de la transition</h1>
<% if current_user %>
<p>Pour louer un livre, <strong>contactez directement le propriétaire via son email</strong></p>
<% else %>
<p>Pour les habitants de La-Chapelle-sur-Erdre et ses environs : prêt de livres entre particulier sur le sujet de la transition. Pas besoin de Facebook ni Google, une adresse e-mail suffit. Contactez David ou Gaëlle pour utiliser le service.</p>
<% end %>

<table id="main_table" class="books">
  <caption></caption>
  <thead>
    <tr>
      <th align="left">Titre ↓</th>
      <th align="left">Auteur ↓</th>
      <th align="left">Genre ↓</th>
      <% if livres.try('first').try(:[], :proprietaire) %>
      <th align="left">Propriétaire ↓</th>
      <% end %>
    </tr>
  </thead>
  <tbody class="list">
    <% livres.each do |livre| %>
    <tr>
      <td align="left" class="titre"><%= livre[:titre] %></td>
      <td align="left" class="auteur"><%= livre[:auteur] %></td>
      <td align="left" class="genre"><%= livre[:genre] %></td>
      <% if livre.try(:[], :proprietaire) %>
      <td align="left" class="proprietaire"><%= livre[:proprietaire] %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<style type="text/css">
  #main_table_info {
    display: none;
  }
  #main_table th {
    cursor: pointer;
  }
  .add-your-books {
    background-color: #1976d2;
    border-radius: 4px;
    color: #fff;
    cursor: pointer;
    font-weight: 700;
    line-height: 2.3;
    padding: 0em .75em;
    text-decoration: none;
    transition: background-color 250ms ease-in-out;
    user-select: none;
    vertical-align: middle;
    white-space: nowrap;
    height: 37px;
  }
</style>